import type { Lesson } from '@/types/lesson'

export const lessons: Lesson[] = [
  // ─── 2D SHAPES ──────────────────────────────────────────────────────────────
  {
    id: 'circle-area',
    title: 'Area of Circle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Circle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Discover why the area of a circle is πr² by cutting sectors and rearranging them into a rectangle.',
    formula: 'A = πr²',
    formulaLatex: 'A = \\pi r^2',
    color: '#2563EB',
    icon: '○',
    available: true,
    realLifeExamples: [
      'Pizza size comparison',
      'Round table cover',
      'Circular garden area',
      'Water tank base',
      'Coin surface area',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'Start with a circle',
        explanation: 'A circle has a radius r — the distance from the center to any point on the edge.',
        formulaText: 'radius = r',
        visualInstruction: 'Show circle with radius label',
      },
      {
        stepNumber: 2,
        title: 'Cut into equal sectors',
        explanation: 'Imagine cutting the circle like a pizza into many equal slices (sectors). The more slices, the better the result.',
        formulaText: 'n sectors, each with angle = 360°/n',
        visualInstruction: 'Show circle divided into sectors',
      },
      {
        stepNumber: 3,
        title: 'Rearrange the sectors',
        explanation: 'Take all the sectors and arrange them alternating up-down, like interlocking teeth. The shape starts looking like a bumpy rectangle.',
        formulaText: 'Sectors alternated and joined',
        visualInstruction: 'Show sectors being rearranged',
      },
      {
        stepNumber: 4,
        title: 'It becomes a rectangle!',
        explanation: 'As we use more and more sectors, the bumpy shape gets closer and closer to a perfect rectangle.',
        formulaText: 'Shape ≈ rectangle as n → ∞',
        visualInstruction: 'Show sectors forming rectangle',
      },
      {
        stepNumber: 5,
        title: 'Find the height',
        explanation: 'The height of the rectangle equals the radius r of the circle.',
        formulaText: 'height = r',
        visualInstruction: 'Show height = r label',
      },
      {
        stepNumber: 6,
        title: 'Find the base',
        explanation: 'The base of the rectangle equals half of the circumference of the circle.',
        formulaText: 'base = C/2 = 2πr/2 = πr',
        visualInstruction: 'Show base = πr label',
      },
      {
        stepNumber: 7,
        title: 'Calculate the area',
        explanation: 'Area of rectangle = base × height = πr × r = πr²',
        formulaText: 'A = base × height = πr × r = πr²',
        visualInstruction: 'Show final formula highlighted',
      },
    ],
    routePath: '/geometry/circle',
  },
  {
    id: 'triangle-area',
    title: 'Area of Triangle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Triangle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'See why the area of a triangle is ½ × base × height using the parallelogram duplication trick.',
    formula: 'A = ½bh',
    formulaLatex: 'A = \\frac{1}{2}bh',
    color: '#059669',
    icon: '△',
    available: true,
    realLifeExamples: [
      'Triangular roof surface',
      'Sail of a boat',
      'Road warning signs',
      'Sandwich cut diagonally',
      'Pyramid face',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'Start with a triangle',
        explanation: 'Any triangle has a base b and a perpendicular height h.',
        formulaText: 'base = b, height = h',
        visualInstruction: 'Show triangle with base and height',
      },
      {
        stepNumber: 2,
        title: 'Make a copy',
        explanation: 'Create an identical copy of the triangle.',
        formulaText: 'Copy = same triangle',
        visualInstruction: 'Show duplicate triangle',
      },
      {
        stepNumber: 3,
        title: 'Flip and attach',
        explanation: 'Rotate the copy 180° and attach it to the original triangle.',
        formulaText: 'Flip 180°',
        visualInstruction: 'Show flipped triangle being attached',
      },
      {
        stepNumber: 4,
        title: 'Forms a parallelogram',
        explanation: 'The two triangles together form a parallelogram with base b and height h.',
        formulaText: 'Two triangles = 1 parallelogram',
        visualInstruction: 'Show parallelogram formed',
      },
      {
        stepNumber: 5,
        title: 'Calculate the area',
        explanation: 'Area of parallelogram = b × h, so area of one triangle = half of that.',
        formulaText: 'A = (b × h) / 2 = ½bh',
        visualInstruction: 'Show formula derivation',
      },
    ],
    routePath: '/geometry/triangle',
  },
  {
    id: 'parallelogram-area',
    title: 'Area of Parallelogram',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Parallelogram',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Learn why Area = base × height by cutting and rearranging a parallelogram into a rectangle.',
    formula: 'A = b × h',
    formulaLatex: 'A = b \\times h',
    color: '#D97706',
    icon: '▱',
    available: true,
    realLifeExamples: [
      'Parallelogram-shaped fields',
      'Some window panes',
      'Decorative tiles',
      'Parallelogram plots of land',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'Start with a parallelogram',
        explanation: 'A parallelogram has a base b and a perpendicular height h (not the slant side).',
        formulaText: 'base = b, height = h',
        visualInstruction: 'Show parallelogram with labels',
      },
      {
        stepNumber: 2,
        title: 'Cut a triangle from one side',
        explanation: 'Cut a right triangle from the left side by drawing a vertical line down from the top-left corner.',
        formulaText: 'Cut vertical line from top-left',
        visualInstruction: 'Show cut triangle highlighted',
      },
      {
        stepNumber: 3,
        title: 'Move the triangle',
        explanation: 'Take the cut triangle and slide it to the right side of the shape.',
        formulaText: 'Move triangle to right side',
        visualInstruction: 'Show triangle sliding right',
      },
      {
        stepNumber: 4,
        title: 'Forms a rectangle',
        explanation: 'The parallelogram becomes a perfect rectangle with the same base b and height h.',
        formulaText: 'Rectangle: same base b, same height h',
        visualInstruction: 'Show final rectangle',
      },
      {
        stepNumber: 5,
        title: 'Area is the same',
        explanation: 'We only moved pieces, so the area did not change. Area = b × h.',
        formulaText: 'A = b × h',
        visualInstruction: 'Show formula result',
      },
    ],
    routePath: '/geometry/parallelogram',
  },
  {
    id: 'trapezium-area',
    title: 'Area of Trapezium',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Trapezium',
    shapeType: '2D',
    difficulty: 'Intermediate',
    description: 'Understand the trapezium area formula by duplicating and joining two trapeziums into a parallelogram.',
    formula: 'A = ½(a+b)h',
    formulaLatex: 'A = \\frac{1}{2}(a+b)h',
    color: '#7C3AED',
    icon: '⬡',
    available: true,
    realLifeExamples: [
      'Cross-section of a river bed',
      'Trapezoidal fields',
      'Embankment cross-sections',
      'Some roof cross-sections',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'Start with a trapezium',
        explanation: 'A trapezium has two parallel sides: top side a (shorter) and bottom side b (longer), with height h.',
        formulaText: 'top = a, bottom = b, height = h',
        visualInstruction: 'Show trapezium with labels',
      },
      {
        stepNumber: 2,
        title: 'Make a copy and flip it',
        explanation: 'Create an identical copy and rotate it 180°.',
        formulaText: 'Rotate copy 180°',
        visualInstruction: 'Show flipped copy',
      },
      {
        stepNumber: 3,
        title: 'Join them together',
        explanation: 'Attach the flipped copy to the original. They fit perfectly to form a parallelogram.',
        formulaText: 'Two trapeziums = 1 parallelogram',
        visualInstruction: 'Show parallelogram formed',
      },
      {
        stepNumber: 4,
        title: 'Parallelogram dimensions',
        explanation: 'The parallelogram has base = (a + b) and height = h.',
        formulaText: 'Parallelogram: base = (a+b), height = h',
        visualInstruction: 'Show parallelogram dimensions',
      },
      {
        stepNumber: 5,
        title: 'Calculate one trapezium',
        explanation: 'Area of parallelogram = (a+b)×h, so area of ONE trapezium = half of that.',
        formulaText: 'A = (a+b)×h / 2 = ½(a+b)h',
        visualInstruction: 'Show final formula',
      },
    ],
    routePath: '/geometry/trapezium',
  },
  {
    id: 'rectangle-area',
    title: 'Area of Rectangle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Rectangle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Understand the area of a rectangle by counting unit squares.',
    formula: 'A = l × w',
    formulaLatex: 'A = l \\times w',
    color: '#0891B2',
    icon: '▭',
    available: false,
    realLifeExamples: ['Room floor', 'Book cover', 'Screen size', 'Field'],
    derivationSteps: [],
    routePath: '/geometry/rectangle',
  },
  {
    id: 'square-area',
    title: 'Area of Square',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Square',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Explore the area formula for a square.',
    formula: 'A = a²',
    formulaLatex: 'A = a^2',
    color: '#0891B2',
    icon: '□',
    available: false,
    realLifeExamples: ['Floor tiles', 'Chess board', 'Square fields'],
    derivationSteps: [],
    routePath: '/geometry/square',
  },
  {
    id: 'semicircle-area',
    title: 'Area of Semicircle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Semicircle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Understand the semicircle area as half of a circle.',
    formula: 'A = ½πr²',
    formulaLatex: 'A = \\frac{1}{2}\\pi r^2',
    color: '#0284C7',
    icon: '◗',
    available: false,
    realLifeExamples: ['Tunnel entrance', 'Archway', 'Half-pipe'],
    derivationSteps: [],
    routePath: '/geometry/semicircle',
  },
  {
    id: 'sector-area',
    title: 'Area of Sector',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Sector',
    shapeType: '2D',
    difficulty: 'Intermediate',
    description: 'Learn the area formula for a sector of a circle.',
    formula: 'A = ½r²θ',
    formulaLatex: 'A = \\frac{1}{2}r^2\\theta',
    color: '#7C3AED',
    icon: '◔',
    available: false,
    realLifeExamples: ['Pizza slice', 'Clock sector', 'Pie chart segment'],
    derivationSteps: [],
    routePath: '/geometry/sector',
  },

  // ─── 3D SHAPES ──────────────────────────────────────────────────────────────
  {
    id: 'cube',
    title: 'Cube: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cube',
    shapeType: '3D',
    difficulty: 'Beginner',
    description: 'Explore how cube surface area (6a²) and volume (a³) are derived by unfolding its net.',
    formula: 'SA = 6a²,  V = a³',
    formulaLatex: 'SA = 6a^2, \\quad V = a^3',
    color: '#DC2626',
    icon: '⬛',
    available: true,
    realLifeExamples: [
      'Ice cube',
      'Sugar cube',
      'Rubik\'s cube',
      'Dice',
      'Building blocks',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'A cube has 6 faces',
        explanation: 'Every cube has exactly 6 square faces, all identical.',
        formulaText: '6 faces, each with area = a × a = a²',
        visualInstruction: 'Show cube with 6 faces highlighted',
      },
      {
        stepNumber: 2,
        title: 'Unfold (net) the cube',
        explanation: 'Unfold the cube like a cardboard box. You get 6 squares spread flat.',
        formulaText: 'Net = 6 squares',
        visualInstruction: 'Show cube net animation',
      },
      {
        stepNumber: 3,
        title: 'Surface area',
        explanation: 'Total surface area = sum of all 6 faces = 6 × a²',
        formulaText: 'SA = 6a²',
        visualInstruction: 'Show surface area calculation',
      },
      {
        stepNumber: 4,
        title: 'Volume by stacking layers',
        explanation: 'Think of filling the cube with unit cubes. Each layer has a × a = a² unit cubes, and there are a layers.',
        formulaText: 'V = a² × a = a³',
        visualInstruction: 'Show cube filling with unit cubes',
      },
    ],
    routePath: '/geometry/cube',
  },
  {
    id: 'cuboid',
    title: 'Cuboid: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cuboid',
    shapeType: '3D',
    difficulty: 'Beginner',
    description: 'Understand cuboid surface area [2(lw+wh+lh)] and volume (lwh) by unfolding its net.',
    formula: 'SA = 2(lw+wh+lh),  V = lwh',
    formulaLatex: 'SA = 2(lw+wh+lh), \\quad V = lwh',
    color: '#EA580C',
    icon: '▬',
    available: true,
    realLifeExamples: ['Brick', 'Shoebox', 'Fridge', 'Room', 'Book'],
    derivationSteps: [
      {
        stepNumber: 1,
        title: '3 pairs of faces',
        explanation: 'A cuboid has 3 pairs of opposite faces: l×w (top/bottom), w×h (front/back), l×h (left/right).',
        formulaText: 'Face 1: l×w (×2), Face 2: w×h (×2), Face 3: l×h (×2)',
        visualInstruction: 'Show 3 pairs of faces',
      },
      {
        stepNumber: 2,
        title: 'Surface area',
        explanation: 'Add all 6 faces: 2(lw) + 2(wh) + 2(lh) = 2(lw+wh+lh)',
        formulaText: 'SA = 2(lw+wh+lh)',
        visualInstruction: 'Show net with labeled faces',
      },
      {
        stepNumber: 3,
        title: 'Volume by layers',
        explanation: 'Volume = length × width × height (counting how many unit cubes fit inside).',
        formulaText: 'V = l × w × h',
        visualInstruction: 'Show layer stacking',
      },
    ],
    routePath: '/geometry/cuboid',
  },
  {
    id: 'cylinder',
    title: 'Cylinder: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cylinder',
    shapeType: '3D',
    difficulty: 'Intermediate',
    description: 'Visualize cylinder volume (πr²h) and surface area (2πr²+2πrh) by stacking circles and unrolling.',
    formula: 'V = πr²h,  SA = 2πr(r+h)',
    formulaLatex: 'V = \\pi r^2 h, \\quad SA = 2\\pi r(r+h)',
    color: '#0891B2',
    icon: '⬤',
    available: true,
    realLifeExamples: [
      'Tin can',
      'Water pipe',
      'Rolling pin',
      'Pillar/column',
      'Battery',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'Stack circular layers',
        explanation: 'A cylinder is just many circular layers of radius r stacked to height h.',
        formulaText: 'Base area = πr²',
        visualInstruction: 'Show circle stacking animation',
      },
      {
        stepNumber: 2,
        title: 'Volume',
        explanation: 'Volume = base area × height = πr² × h',
        formulaText: 'V = πr²h',
        visualInstruction: 'Show full cylinder with volume label',
      },
      {
        stepNumber: 3,
        title: 'Unroll the curved surface',
        explanation: 'If you peel the curved surface and unroll it, you get a rectangle. Width = circumference = 2πr, Height = h.',
        formulaText: 'Curved SA = 2πr × h = 2πrh',
        visualInstruction: 'Show unrolling animation',
      },
      {
        stepNumber: 4,
        title: 'Add two circular ends',
        explanation: 'Top and bottom are two circles, each with area πr².',
        formulaText: 'Two circles = 2πr²',
        visualInstruction: 'Show net with two circles',
      },
      {
        stepNumber: 5,
        title: 'Total surface area',
        explanation: 'Total SA = curved surface + two circles = 2πrh + 2πr² = 2πr(h+r)',
        formulaText: 'SA = 2πr(r+h)',
        visualInstruction: 'Show complete net',
      },
    ],
    routePath: '/geometry/cylinder',
  },
  {
    id: 'cone',
    title: 'Cone: Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cone',
    shapeType: '3D',
    difficulty: 'Intermediate',
    description: 'Discover why cone volume is exactly ⅓ of cylinder volume through a visual filling experiment.',
    formula: 'V = ⅓πr²h',
    formulaLatex: 'V = \\frac{1}{3}\\pi r^2 h',
    color: '#7C3AED',
    icon: '▽',
    available: true,
    realLifeExamples: [
      'Ice cream cone',
      'Traffic cone',
      'Party hat',
      'Volcano shape',
      'Pyramid (approximately)',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'Cone and cylinder with same base and height',
        explanation: 'Take a cone and a cylinder that have exactly the same base radius r and height h.',
        formulaText: 'Same r, same h',
        visualInstruction: 'Show cone next to cylinder',
      },
      {
        stepNumber: 2,
        title: 'Fill the cone',
        explanation: 'Fill the cone with water (or sand).',
        formulaText: 'Cone volume = ?',
        visualInstruction: 'Show cone being filled',
      },
      {
        stepNumber: 3,
        title: 'Pour into cylinder — 1st time',
        explanation: 'Pour the cone\'s contents into the cylinder. It fills only 1/3 of the cylinder.',
        formulaText: '1 cone = 1/3 cylinder',
        visualInstruction: 'Show cylinder filling to 1/3',
      },
      {
        stepNumber: 4,
        title: 'Pour again — 2nd and 3rd times',
        explanation: 'Fill and pour two more times. After exactly 3 pours, the cylinder is completely full.',
        formulaText: '3 cones = 1 cylinder',
        visualInstruction: 'Show cylinder filling to 2/3, then full',
      },
      {
        stepNumber: 5,
        title: 'Therefore cone volume',
        explanation: 'Since 3 cones = 1 cylinder, 1 cone = ⅓ of cylinder. Cylinder volume = πr²h, so cone = ⅓πr²h.',
        formulaText: 'V = ⅓πr²h',
        visualInstruction: 'Show final formula',
      },
    ],
    routePath: '/geometry/cone',
  },
  {
    id: 'sphere',
    title: 'Sphere: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Sphere',
    shapeType: '3D',
    difficulty: 'Advanced',
    description: 'Explore sphere surface area (4πr²) and volume (4/3πr³) through visual comparison and Archimedes\' insight.',
    formula: 'SA = 4πr²,  V = 4/3πr³',
    formulaLatex: 'SA = 4\\pi r^2, \\quad V = \\frac{4}{3}\\pi r^3',
    color: '#DB2777',
    icon: '●',
    available: true,
    realLifeExamples: [
      'Earth and planets',
      'Basketball',
      'Bubble',
      'Orange',
      'Ball bearing',
    ],
    derivationSteps: [
      {
        stepNumber: 1,
        title: 'Surface area = 4 circles',
        explanation: 'The surface area of a sphere equals exactly 4 circles of the same radius r.',
        formulaText: 'SA = 4 × πr² = 4πr²',
        visualInstruction: 'Show sphere with 4 circles beside it',
      },
      {
        stepNumber: 2,
        title: 'Sphere inside a cylinder',
        explanation: 'Place the sphere inside a cylinder with radius r and height 2r.',
        formulaText: 'Cylinder: radius=r, height=2r',
        visualInstruction: 'Show sphere inside cylinder',
      },
      {
        stepNumber: 3,
        title: 'Cylinder volume',
        explanation: 'Cylinder volume = πr² × 2r = 2πr³',
        formulaText: 'V_cylinder = 2πr³',
        visualInstruction: 'Show cylinder volume calculation',
      },
      {
        stepNumber: 4,
        title: 'Sphere is ⅔ of cylinder',
        explanation: 'Archimedes proved that the sphere fills exactly ⅔ of the surrounding cylinder.',
        formulaText: 'V_sphere = ⅔ × V_cylinder = ⅔ × 2πr³ = 4/3πr³',
        visualInstruction: 'Show sphere volume relationship',
      },
    ],
    routePath: '/geometry/sphere',
  },
  {
    id: 'hemisphere',
    title: 'Hemisphere: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Hemisphere',
    shapeType: '3D',
    difficulty: 'Intermediate',
    description: 'Understand hemisphere formulas as half of a sphere.',
    formula: 'SA = 3πr²,  V = ⅔πr³',
    formulaLatex: 'SA = 3\\pi r^2, \\quad V = \\frac{2}{3}\\pi r^3',
    color: '#BE185D',
    icon: '◗',
    available: false,
    realLifeExamples: ['Bowl', 'Dome', 'Igloo'],
    derivationSteps: [],
    routePath: '/geometry/hemisphere',
  },
  {
    id: 'pyramid',
    title: 'Pyramid: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Pyramid',
    shapeType: '3D',
    difficulty: 'Advanced',
    description: 'Learn pyramid volume (⅓ × base × height) and surface area.',
    formula: 'V = ⅓Bh',
    formulaLatex: 'V = \\frac{1}{3}Bh',
    color: '#92400E',
    icon: '▲',
    available: false,
    realLifeExamples: ['Egyptian pyramids', 'Tent shape', 'Cheese wedge'],
    derivationSteps: [],
    routePath: '/geometry/pyramid',
  },
]

export function getLessonById(id: string): Lesson | undefined {
  return lessons.find((l) => l.id === id)
}

export function getLessonByShape(shape: string): Lesson | undefined {
  return lessons.find((l) => l.shape.toLowerCase() === shape.toLowerCase())
}

export function getLessonByRoute(route: string): Lesson | undefined {
  return lessons.find((l) => l.routePath === route)
}

export const shapeLessons2D = lessons.filter((l) => l.shapeType === '2D')
export const shapeLessons3D = lessons.filter((l) => l.shapeType === '3D')
export const availableLessons = lessons.filter((l) => l.available)
