import type { Lesson } from '@/types/lesson'

export const lessons: Lesson[] = [
  // ─── 2D SHAPES ──────────────────────────────────────────────────────────────
  {
    id: 'circle-area',
    title: 'Area of Circle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Circle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Discover why the area of a circle is πr² by cutting sectors and rearranging them into a rectangle.',
    formula: 'A = πr²',
    formulaLatex: 'A = \\pi r^2',
    color: '#2563EB',
    icon: '○',
    available: true,
    realLifeExamples: ['Pizza size comparison', 'Round table cover', 'Circular garden area', 'Water tank base', 'Coin surface area'],
    derivationSteps: [
      { stepNumber: 1, title: 'Start with a circle', explanation: 'A circle has a radius r — the distance from the center to any point on the edge.', formulaText: 'radius = r' },
      { stepNumber: 2, title: 'Cut into equal sectors', explanation: 'Imagine cutting the circle like a pizza into many equal slices (sectors).', formulaText: 'n sectors, each with angle = 360°/n' },
      { stepNumber: 3, title: 'Rearrange the sectors', explanation: 'Arrange them alternating up-down. The shape starts looking like a bumpy rectangle.', formulaText: 'Sectors alternated and joined' },
      { stepNumber: 4, title: 'It becomes a rectangle!', explanation: 'As we use more sectors, the bumpy shape gets closer to a perfect rectangle.', formulaText: 'Shape ≈ rectangle as n → ∞' },
      { stepNumber: 5, title: 'Find the height', explanation: 'The height of the rectangle equals the radius r.', formulaText: 'height = r' },
      { stepNumber: 6, title: 'Find the base', explanation: 'The base equals half of the circumference = 2πr/2 = πr.', formulaText: 'base = πr' },
      { stepNumber: 7, title: 'Calculate the area', explanation: 'Area = base × height = πr × r = πr²', formulaText: 'A = πr × r = πr²' },
    ],
    routePath: '/geometry/circle',
  },
  {
    id: 'triangle-area',
    title: 'Area of Triangle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Triangle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'See why the area of a triangle is ½ × base × height using the parallelogram duplication trick.',
    formula: 'A = ½bh',
    formulaLatex: 'A = \\frac{1}{2}bh',
    color: '#059669',
    icon: '△',
    available: true,
    realLifeExamples: ['Triangular roof surface', 'Sail of a boat', 'Road warning signs', 'Sandwich cut diagonally', 'Pyramid face'],
    derivationSteps: [
      { stepNumber: 1, title: 'Start with a triangle', explanation: 'Any triangle has a base b and a perpendicular height h.', formulaText: 'base = b, height = h' },
      { stepNumber: 2, title: 'Make a copy', explanation: 'Create an identical copy of the triangle.', formulaText: 'Copy = same triangle' },
      { stepNumber: 3, title: 'Flip and attach', explanation: 'Rotate the copy 180° and attach it to the original.', formulaText: 'Flip 180°' },
      { stepNumber: 4, title: 'Forms a parallelogram', explanation: 'The two triangles form a parallelogram with base b and height h.', formulaText: 'Two triangles = 1 parallelogram' },
      { stepNumber: 5, title: 'Calculate the area', explanation: 'Parallelogram area = b×h, so triangle = ½bh.', formulaText: 'A = ½bh' },
    ],
    routePath: '/geometry/triangle',
  },
  // ── Triangle Sub-Types ────────────────────────────────────────────────────
  {
    id: 'equilateral-triangle',
    title: 'Equilateral Triangle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Equilateral Triangle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'All 3 sides equal. Discover the special area formula A = (√3/4)a² by deriving the height from the equal sides.',
    formula: 'A = (√3/4)a²',
    formulaLatex: 'A = \\frac{\\sqrt{3}}{4}a^2',
    color: '#16a34a',
    icon: '▲',
    available: true,
    parentId: 'triangle-area',
    realLifeExamples: ['Yield/warning signs', 'Pyramid cross-section', 'Billiard rack', 'Truss bridges', 'Crystal structure'],
    derivationSteps: [
      { stepNumber: 1, title: 'All sides equal', explanation: 'An equilateral triangle has all 3 sides equal to a and all 3 angles equal to 60°.', formulaText: 'a = b = c, all angles = 60°' },
      { stepNumber: 2, title: 'Draw the height', explanation: 'The perpendicular from the apex to the base bisects the base exactly, creating two right-angled triangles.', formulaText: 'base is split into two halves of a/2' },
      { stepNumber: 3, title: 'Find height by Pythagoras', explanation: 'In the right triangle: h² + (a/2)² = a². So h² = a² - a²/4 = 3a²/4.', formulaText: 'h = √(a² - (a/2)²) = (√3/2)a' },
      { stepNumber: 4, title: 'Apply ½bh', explanation: 'A = ½ × base × height = ½ × a × (√3/2)a = (√3/4)a²', formulaText: 'A = ½ × a × (√3/2)a = (√3/4)a²' },
    ],
    routePath: '/geometry/equilateral-triangle',
  },
  {
    id: 'isosceles-triangle',
    title: 'Isosceles Triangle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Isosceles Triangle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Two equal sides. See how the axis of symmetry gives you the height, leading to A = ½bh.',
    formula: 'A = ½bh',
    formulaLatex: 'A = \\frac{1}{2}bh',
    color: '#0d9488',
    icon: '▲',
    available: true,
    parentId: 'triangle-area',
    realLifeExamples: ['Eiffel Tower cross-section', 'Isosceles roof truss', 'Kite shape', 'Arrowhead', 'Letter A shape'],
    derivationSteps: [
      { stepNumber: 1, title: 'Two equal sides (legs)', explanation: 'An isosceles triangle has two equal sides called legs (l) and a base (b).', formulaText: 'legs = l, base = b' },
      { stepNumber: 2, title: 'Axis of symmetry', explanation: 'The perpendicular from the apex is also the axis of symmetry and bisects the base into two equal halves (b/2).', formulaText: 'Axis splits base into b/2 and b/2' },
      { stepNumber: 3, title: 'Height by Pythagoras', explanation: 'Using the right triangle formed: h = √(l² - (b/2)²)', formulaText: 'h = √(l² - (b/2)²)' },
      { stepNumber: 4, title: 'Area formula', explanation: 'A = ½ × base × height = ½ × b × √(l² - (b/2)²)', formulaText: 'A = ½bh = ½b√(l² - (b/2)²)' },
    ],
    routePath: '/geometry/isosceles-triangle',
  },
  {
    id: 'scalene-triangle',
    title: 'Scalene Triangle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Scalene Triangle',
    shapeType: '2D',
    difficulty: 'Intermediate',
    description: 'All sides different. Learn Heron\'s formula and see how even irregular triangles follow ½bh.',
    formula: "A = √(s(s-a)(s-b)(s-c))",
    formulaLatex: 'A = \\sqrt{s(s-a)(s-b)(s-c)}',
    color: '#0891b2',
    icon: '▲',
    available: true,
    parentId: 'triangle-area',
    realLifeExamples: ['Irregular land plots', 'Structural bracing', 'Ramp side profile', 'Guitar body shape', 'Navigation triangulation'],
    derivationSteps: [
      { stepNumber: 1, title: 'All three sides different', explanation: 'A scalene triangle has sides a, b, c — all different lengths. No equal sides, no equal angles.', formulaText: 'a ≠ b ≠ c' },
      { stepNumber: 2, title: 'Semi-perimeter s', explanation: 'Calculate the semi-perimeter: s = (a + b + c) / 2', formulaText: 's = (a + b + c) / 2' },
      { stepNumber: 3, title: "Heron's Formula", explanation: 'Heron of Alexandria discovered: Area = √(s·(s-a)·(s-b)·(s-c))', formulaText: 'A = √(s(s-a)(s-b)(s-c))' },
      { stepNumber: 4, title: 'Also A = ½bh', explanation: 'You can also use base b and perpendicular height h. The apex can be anywhere above the base.', formulaText: 'A = ½ × base × height' },
    ],
    routePath: '/geometry/scalene-triangle',
  },
  {
    id: 'parallelogram-area',
    title: 'Area of Parallelogram',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Parallelogram',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Learn why Area = base × height by cutting and rearranging a parallelogram into a rectangle.',
    formula: 'A = b × h',
    formulaLatex: 'A = b \\times h',
    color: '#D97706',
    icon: '▱',
    available: true,
    realLifeExamples: ['Parallelogram-shaped fields', 'Some window panes', 'Decorative tiles', 'Parallelogram plots of land'],
    derivationSteps: [
      { stepNumber: 1, title: 'Start with a parallelogram', explanation: 'A parallelogram has base b and perpendicular height h (not the slant side).', formulaText: 'base = b, height = h' },
      { stepNumber: 2, title: 'Cut a triangle from one side', explanation: 'Cut a right triangle from the left by drawing a vertical line from the top-left corner.', formulaText: 'Cut vertical line from top-left' },
      { stepNumber: 3, title: 'Move the triangle', explanation: 'Slide the cut triangle to the right side.', formulaText: 'Move triangle to right side' },
      { stepNumber: 4, title: 'Forms a rectangle', explanation: 'The parallelogram becomes a rectangle with the same base b and height h.', formulaText: 'Rectangle: same base b, same height h' },
      { stepNumber: 5, title: 'Area is the same', explanation: 'We only moved pieces. Area = b × h.', formulaText: 'A = b × h' },
    ],
    routePath: '/geometry/parallelogram',
  },
  {
    id: 'trapezium-area',
    title: 'Area of Trapezium',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Trapezium',
    shapeType: '2D',
    difficulty: 'Intermediate',
    description: 'Understand the trapezium area formula by duplicating and joining two trapeziums into a parallelogram.',
    formula: 'A = ½(a+b)h',
    formulaLatex: 'A = \\frac{1}{2}(a+b)h',
    color: '#7C3AED',
    icon: '⬡',
    available: true,
    realLifeExamples: ['Cross-section of a river bed', 'Trapezoidal fields', 'Embankment cross-sections', 'Some roof cross-sections'],
    derivationSteps: [
      { stepNumber: 1, title: 'Start with a trapezium', explanation: 'A trapezium has two parallel sides: top (a) and bottom (b), with height h.', formulaText: 'top = a, bottom = b, height = h' },
      { stepNumber: 2, title: 'Make a copy and flip it', explanation: 'Create an identical copy and rotate it 180°.', formulaText: 'Rotate copy 180°' },
      { stepNumber: 3, title: 'Join them together', explanation: 'They fit perfectly to form a parallelogram.', formulaText: 'Two trapeziums = 1 parallelogram' },
      { stepNumber: 4, title: 'Parallelogram dimensions', explanation: 'Base = (a+b), height = h.', formulaText: 'base = (a+b), height = h' },
      { stepNumber: 5, title: 'Calculate one trapezium', explanation: 'Parallelogram area = (a+b)×h, so one trapezium = half.', formulaText: 'A = ½(a+b)h' },
    ],
    routePath: '/geometry/trapezium',
  },
  {
    id: 'rectangle-area',
    title: 'Area of Rectangle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Rectangle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'Understand why area = length × width by counting unit squares that fill the rectangle.',
    formula: 'A = l × w',
    formulaLatex: 'A = l \\times w',
    color: '#0891B2',
    icon: '▭',
    available: true,
    realLifeExamples: ['Room floor', 'Book cover', 'Screen size', 'Football pitch', 'Photo frame'],
    derivationSteps: [
      { stepNumber: 1, title: 'Length and width', explanation: 'A rectangle has length l and width w. All angles are 90°.', formulaText: 'length = l, width = w' },
      { stepNumber: 2, title: 'Fill with unit squares', explanation: 'Place 1×1 unit squares inside. First row has l squares.', formulaText: '1 row = l squares' },
      { stepNumber: 3, title: 'Stack w rows', explanation: 'Fill all w rows. Total squares = l × w.', formulaText: 'w rows × l squares = l×w' },
      { stepNumber: 4, title: 'Area formula', explanation: 'Each unit square has area 1, so total area = l × w.', formulaText: 'A = l × w' },
    ],
    routePath: '/geometry/rectangle',
  },
  {
    id: 'square-area',
    title: 'Area of Square',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Square',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'A special rectangle with all sides equal. See why A = a² by counting a × a unit squares.',
    formula: 'A = a²',
    formulaLatex: 'A = a^2',
    color: '#0369a1',
    icon: '□',
    available: true,
    realLifeExamples: ['Floor tiles', 'Chess board squares', 'Square fields', 'Window panes', 'Post-it notes'],
    derivationSteps: [
      { stepNumber: 1, title: 'All 4 sides equal', explanation: 'A square has all 4 sides equal to a and all angles 90°.', formulaText: 'all sides = a' },
      { stepNumber: 2, title: 'Special rectangle', explanation: 'A square is a rectangle where l = w = a.', formulaText: 'l = w = a' },
      { stepNumber: 3, title: 'Fill with unit squares', explanation: 'Fill with 1×1 unit squares: a rows × a columns.', formulaText: 'a × a = a² squares' },
      { stepNumber: 4, title: 'Area formula', explanation: 'A = a × a = a²', formulaText: 'A = a²' },
    ],
    routePath: '/geometry/square',
  },
  {
    id: 'semicircle-area',
    title: 'Area of Semicircle',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Semicircle',
    shapeType: '2D',
    difficulty: 'Beginner',
    description: 'A semicircle is exactly half a circle. See how A = ½πr² naturally follows from the full circle formula.',
    formula: 'A = ½πr²',
    formulaLatex: 'A = \\frac{1}{2}\\pi r^2',
    color: '#0284C7',
    icon: '◗',
    available: true,
    realLifeExamples: ['Tunnel entrance', 'Archway', 'Half-pipe', 'D-shaped room', 'Stadium end'],
    derivationSteps: [
      { stepNumber: 1, title: 'Start with a full circle', explanation: 'A full circle with radius r has area A = πr².', formulaText: 'Circle area = πr²' },
      { stepNumber: 2, title: 'Cut exactly in half', explanation: 'A diameter line cuts the circle into two equal semicircles.', formulaText: 'Diameter = 2r' },
      { stepNumber: 3, title: 'Semicircle = half', explanation: 'Each semicircle is exactly ½ of the full circle.', formulaText: 'Semicircle = ½ × πr²' },
      { stepNumber: 4, title: 'Perimeter', explanation: 'Perimeter = curved arc (πr) + straight diameter (2r) = πr + 2r.', formulaText: 'P = πr + 2r = r(π + 2)' },
    ],
    routePath: '/geometry/semicircle',
  },
  {
    id: 'sector-area',
    title: 'Area of Sector',
    subject: 'Geometry',
    category: '2D Shape',
    shape: 'Sector',
    shapeType: '2D',
    difficulty: 'Intermediate',
    description: 'A sector is a "pizza slice" of a circle. Discover how the area scales proportionally with the angle θ.',
    formula: 'A = (θ/360)πr²',
    formulaLatex: 'A = \\frac{\\theta}{360}\\pi r^2',
    color: '#7C3AED',
    icon: '◔',
    available: true,
    realLifeExamples: ['Pizza slice', 'Clock sector', 'Pie chart segment', 'Fan blade', 'Spotlight cone (2D)'],
    derivationSteps: [
      { stepNumber: 1, title: 'Full circle = 360°', explanation: 'A full circle has angle 360° and area πr².', formulaText: 'Full circle: 360°, A = πr²' },
      { stepNumber: 2, title: 'Sector is a fraction', explanation: 'A sector with angle θ is θ/360 of the full circle.', formulaText: 'Fraction = θ/360' },
      { stepNumber: 3, title: 'Scale the area', explanation: 'Sector area = fraction × full circle area.', formulaText: 'A = (θ/360) × πr²' },
      { stepNumber: 4, title: 'In radians', explanation: 'If θ is in radians (full circle = 2π), then A = ½r²θ.', formulaText: 'A = ½r²θ (radians)' },
    ],
    routePath: '/geometry/sector',
  },

  // ─── 3D SHAPES ──────────────────────────────────────────────────────────────
  {
    id: 'cube',
    title: 'Cube: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cube',
    shapeType: '3D',
    difficulty: 'Beginner',
    description: 'Explore how cube surface area (6a²) and volume (a³) are derived by unfolding its net.',
    formula: 'SA = 6a²,  V = a³',
    color: '#DC2626',
    icon: '⬛',
    available: true,
    realLifeExamples: ['Ice cube', 'Sugar cube', "Rubik's cube", 'Dice', 'Building blocks'],
    derivationSteps: [
      { stepNumber: 1, title: 'A cube has 6 faces', explanation: 'Every cube has exactly 6 square faces, all identical with area a².', formulaText: '6 faces, each = a²' },
      { stepNumber: 2, title: 'Unfold the cube', explanation: 'Unfold like a cardboard box to get 6 squares spread flat.', formulaText: 'Net = 6 squares' },
      { stepNumber: 3, title: 'Surface area', explanation: 'SA = 6 × a²', formulaText: 'SA = 6a²' },
      { stepNumber: 4, title: 'Volume by stacking layers', explanation: 'Each layer has a² unit cubes, and there are a layers.', formulaText: 'V = a² × a = a³' },
    ],
    routePath: '/geometry/cube',
  },
  {
    id: 'cuboid',
    title: 'Cuboid: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cuboid',
    shapeType: '3D',
    difficulty: 'Beginner',
    description: 'Understand cuboid SA [2(lw+wh+lh)] and volume (lwh) by unfolding its net.',
    formula: 'SA = 2(lw+wh+lh)',
    color: '#EA580C',
    icon: '▬',
    available: true,
    realLifeExamples: ['Brick', 'Shoebox', 'Fridge', 'Room', 'Book'],
    derivationSteps: [
      { stepNumber: 1, title: '3 pairs of faces', explanation: '3 pairs: l×w (top/bottom), w×h (front/back), l×h (left/right).', formulaText: '3 pairs × 2 = 6 faces' },
      { stepNumber: 2, title: 'Surface area', explanation: '2(lw) + 2(wh) + 2(lh) = 2(lw+wh+lh)', formulaText: 'SA = 2(lw+wh+lh)' },
      { stepNumber: 3, title: 'Volume', explanation: 'V = length × width × height', formulaText: 'V = lwh' },
    ],
    routePath: '/geometry/cuboid',
  },
  {
    id: 'cylinder',
    title: 'Cylinder: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cylinder',
    shapeType: '3D',
    difficulty: 'Intermediate',
    description: 'Visualize cylinder volume (πr²h) and surface area by stacking circles and unrolling.',
    formula: 'V = πr²h,  SA = 2πr(r+h)',
    color: '#0891B2',
    icon: '⬤',
    available: true,
    realLifeExamples: ['Tin can', 'Water pipe', 'Rolling pin', 'Pillar', 'Battery'],
    derivationSteps: [
      { stepNumber: 1, title: 'Stack circular layers', explanation: 'A cylinder is circles of radius r stacked to height h.', formulaText: 'Base area = πr²' },
      { stepNumber: 2, title: 'Volume', explanation: 'V = base area × height = πr²h', formulaText: 'V = πr²h' },
      { stepNumber: 3, title: 'Unroll the curved surface', explanation: 'Peeling the curved surface gives a rectangle: width = 2πr, height = h.', formulaText: 'Curved SA = 2πrh' },
      { stepNumber: 4, title: 'Add two circular ends', explanation: 'Top and bottom = 2 × πr²', formulaText: 'Two circles = 2πr²' },
      { stepNumber: 5, title: 'Total surface area', explanation: '2πrh + 2πr² = 2πr(h+r)', formulaText: 'SA = 2πr(r+h)' },
    ],
    routePath: '/geometry/cylinder',
  },
  {
    id: 'cone',
    title: 'Cone: Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Cone',
    shapeType: '3D',
    difficulty: 'Intermediate',
    description: 'Discover why cone volume is exactly ⅓ of cylinder volume through a visual filling experiment.',
    formula: 'V = ⅓πr²h',
    color: '#7C3AED',
    icon: '▽',
    available: true,
    realLifeExamples: ['Ice cream cone', 'Traffic cone', 'Party hat', 'Volcano', 'Pyramid (approximately)'],
    derivationSteps: [
      { stepNumber: 1, title: 'Cone and cylinder side by side', explanation: 'Same base radius r and height h.', formulaText: 'Same r, same h' },
      { stepNumber: 2, title: 'Fill the cone', explanation: 'Fill with water/sand.', formulaText: 'Cone volume = ?' },
      { stepNumber: 3, title: 'Pour — 1st time', explanation: 'Fills 1/3 of the cylinder.', formulaText: '1 cone = 1/3 cylinder' },
      { stepNumber: 4, title: 'Pour — 2nd and 3rd', explanation: 'After 3 pours, cylinder is completely full.', formulaText: '3 cones = 1 cylinder' },
      { stepNumber: 5, title: 'Therefore cone volume', explanation: '3 cones = 1 cylinder, so V = ⅓πr²h.', formulaText: 'V = ⅓πr²h' },
    ],
    routePath: '/geometry/cone',
  },
  {
    id: 'sphere',
    title: 'Sphere: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Sphere',
    shapeType: '3D',
    difficulty: 'Advanced',
    description: "Explore sphere surface area (4πr²) and volume (4/3πr³) through Archimedes' insight.",
    formula: 'SA = 4πr²,  V = 4/3πr³',
    color: '#DB2777',
    icon: '●',
    available: true,
    realLifeExamples: ['Earth and planets', 'Basketball', 'Bubble', 'Orange', 'Ball bearing'],
    derivationSteps: [
      { stepNumber: 1, title: 'Surface area = 4 circles', explanation: 'SA equals exactly 4 circles of radius r.', formulaText: 'SA = 4πr²' },
      { stepNumber: 2, title: 'Sphere inside a cylinder', explanation: 'Cylinder with radius r and height 2r.', formulaText: 'Cylinder: r, h=2r' },
      { stepNumber: 3, title: 'Cylinder volume', explanation: 'V_cylinder = 2πr³', formulaText: 'V_cylinder = 2πr³' },
      { stepNumber: 4, title: 'Sphere is ⅔ of cylinder', explanation: 'V_sphere = ⅔ × 2πr³ = 4/3πr³', formulaText: 'V = 4/3πr³' },
    ],
    routePath: '/geometry/sphere',
  },
  {
    id: 'hemisphere',
    title: 'Hemisphere: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Hemisphere',
    shapeType: '3D',
    difficulty: 'Intermediate',
    description: 'A hemisphere is half a sphere. See how SA = 3πr² and V = ⅔πr³ are derived from the full sphere.',
    formula: 'SA = 3πr²,  V = ⅔πr³',
    formulaLatex: 'SA = 3\\pi r^2, \\quad V = \\frac{2}{3}\\pi r^3',
    color: '#BE185D',
    icon: '◗',
    available: true,
    realLifeExamples: ['Bowl', 'Dome building', 'Igloo', 'Satellite dish', 'Half-melon'],
    derivationSteps: [
      { stepNumber: 1, title: 'Hemisphere = half sphere', explanation: 'Cut a sphere of radius r in half through its center.', formulaText: 'Hemisphere radius = r' },
      { stepNumber: 2, title: 'Curved surface area', explanation: 'Curved surface = half the sphere SA = 4πr²/2 = 2πr².', formulaText: 'Curved SA = 2πr²' },
      { stepNumber: 3, title: 'Flat circular base', explanation: 'The cut creates a flat circle of radius r with area πr².', formulaText: 'Flat base = πr²' },
      { stepNumber: 4, title: 'Total surface area', explanation: '2πr² + πr² = 3πr²', formulaText: 'Total SA = 3πr²' },
      { stepNumber: 5, title: 'Volume', explanation: 'Volume = half sphere volume = (4/3πr³)/2 = ⅔πr³', formulaText: 'V = ⅔πr³' },
    ],
    routePath: '/geometry/hemisphere',
  },
  {
    id: 'pyramid',
    title: 'Pyramid: Surface Area & Volume',
    subject: 'Geometry',
    category: '3D Shape',
    shape: 'Pyramid',
    shapeType: '3D',
    difficulty: 'Advanced',
    description: 'Learn pyramid volume (⅓Bh) and see why it equals exactly ⅓ of the surrounding prism.',
    formula: 'V = ⅓Bh,  SA = B + ½Pl',
    formulaLatex: 'V = \\frac{1}{3}Bh',
    color: '#92400E',
    icon: '▲',
    available: true,
    realLifeExamples: ['Egyptian pyramids', 'Tent shape', 'Cheese wedge', 'Mountain peak', 'Roof hip'],
    derivationSteps: [
      { stepNumber: 1, title: 'Square base pyramid', explanation: 'A square pyramid has a square base (side b) and apex height h.', formulaText: 'base = b², height = h' },
      { stepNumber: 2, title: 'Volume = ⅓ of prism', explanation: 'Three identical pyramids fill one prism. So V = ⅓ × base × height.', formulaText: 'V = ⅓b²h' },
      { stepNumber: 3, title: 'Slant height', explanation: 'Slant height l = √(h² + (b/2)²) — distance from midpoint of base edge to apex.', formulaText: 'l = √(h² + (b/2)²)' },
      { stepNumber: 4, title: 'Surface area', explanation: 'SA = base + 4 triangular faces. Each triangle = ½bl.', formulaText: 'SA = b² + 4×(½bl) = b² + 2bl' },
    ],
    routePath: '/geometry/pyramid',
  },
]

export function getLessonById(id: string): Lesson | undefined {
  return lessons.find((l) => l.id === id)
}

export function getLessonByShape(shape: string): Lesson | undefined {
  const normalized = shape.toLowerCase().replace(/-/g, ' ')
  return lessons.find((l) => l.shape.toLowerCase() === normalized)
}

export function getLessonByRoute(route: string): Lesson | undefined {
  return lessons.find((l) => l.routePath === route)
}

export const shapeLessons2D = lessons.filter((l) => l.shapeType === '2D')
export const shapeLessons3D = lessons.filter((l) => l.shapeType === '3D')
export const availableLessons = lessons.filter((l) => l.available)
