import type { Quiz } from '@/types/quiz'

export const quizzes: Quiz[] = [
  {
    id: 'quiz-circle',
    lessonId: 'circle-area',
    title: 'Circle Area Quiz',
    difficulty: 'Beginner',
    questions: [
      {
        id: 'q-circle-1',
        quizId: 'quiz-circle',
        questionText: 'A circle has radius 7 cm. What is its area? (Use π = 22/7)',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '44 cm²' },
          { id: 'b', text: '154 cm²' },
          { id: 'c', text: '22 cm²' },
          { id: 'd', text: '49 cm²' },
        ],
        correctAnswer: 'b',
        explanation: 'Area = πr² = (22/7) × 7 × 7 = 22 × 7 = 154 cm²',
        topicTag: 'circle-area',
        difficulty: 'easy',
      },
      {
        id: 'q-circle-2',
        quizId: 'quiz-circle',
        questionText: 'What is the formula for the area of a circle?',
        questionType: 'formula-select',
        options: [
          { id: 'a', text: 'A = 2πr' },
          { id: 'b', text: 'A = πr²' },
          { id: 'c', text: 'A = πd' },
          { id: 'd', text: 'A = 2πr²' },
        ],
        correctAnswer: 'b',
        explanation: 'The area formula is A = πr², where r is the radius.',
        topicTag: 'circle-formula',
        difficulty: 'easy',
      },
      {
        id: 'q-circle-3',
        quizId: 'quiz-circle',
        questionText: 'In the sector rearrangement method, what does the HEIGHT of the rectangle equal?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: 'The diameter (2r)' },
          { id: 'b', text: 'The circumference (2πr)' },
          { id: 'c', text: 'The radius (r)' },
          { id: 'd', text: 'Half the circumference (πr)' },
        ],
        correctAnswer: 'c',
        explanation: 'When sectors are rearranged into a rectangle, the height of that rectangle equals the radius r of the circle.',
        topicTag: 'circle-derivation',
        difficulty: 'medium',
      },
      {
        id: 'q-circle-4',
        quizId: 'quiz-circle',
        questionText: 'A circular garden has an area of 314 m². What is its radius? (Use π ≈ 3.14)',
        questionType: 'numerical',
        correctAnswer: '10',
        explanation: 'A = πr²  →  314 = 3.14 × r²  →  r² = 100  →  r = 10 m',
        topicTag: 'circle-area',
        difficulty: 'medium',
      },
      {
        id: 'q-circle-5',
        quizId: 'quiz-circle',
        questionText: 'If the radius of a circle is doubled, its area becomes:',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: 'Double' },
          { id: 'b', text: 'Triple' },
          { id: 'c', text: '4 times' },
          { id: 'd', text: 'Same' },
        ],
        correctAnswer: 'c',
        explanation: 'Area = πr². If radius doubles to 2r, new area = π(2r)² = 4πr². Area becomes 4 times larger.',
        topicTag: 'circle-area',
        difficulty: 'hard',
      },
    ],
  },
  {
    id: 'quiz-triangle',
    lessonId: 'triangle-area',
    title: 'Triangle Area Quiz',
    difficulty: 'Beginner',
    questions: [
      {
        id: 'q-tri-1',
        quizId: 'quiz-triangle',
        questionText: 'A triangle has base = 12 cm and height = 8 cm. What is its area?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '96 cm²' },
          { id: 'b', text: '48 cm²' },
          { id: 'c', text: '24 cm²' },
          { id: 'd', text: '40 cm²' },
        ],
        correctAnswer: 'b',
        explanation: 'Area = ½ × base × height = ½ × 12 × 8 = 48 cm²',
        topicTag: 'triangle-area',
        difficulty: 'easy',
      },
      {
        id: 'q-tri-2',
        quizId: 'quiz-triangle',
        questionText: 'Why do we multiply by ½ in the triangle area formula?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: 'Because a triangle has 3 sides' },
          { id: 'b', text: 'Because two identical triangles form a parallelogram' },
          { id: 'c', text: 'Because height is half the base' },
          { id: 'd', text: 'It is just a convention' },
        ],
        correctAnswer: 'b',
        explanation: 'Two identical triangles can be arranged to form a parallelogram (Area = bh). So one triangle = ½bh.',
        topicTag: 'triangle-derivation',
        difficulty: 'medium',
      },
      {
        id: 'q-tri-3',
        quizId: 'quiz-triangle',
        questionText: 'A right triangle has legs of 6 cm and 8 cm. What is its area?',
        questionType: 'numerical',
        correctAnswer: '24',
        explanation: 'For a right triangle, the two legs are the base and height. Area = ½ × 6 × 8 = 24 cm²',
        topicTag: 'triangle-area',
        difficulty: 'easy',
      },
      {
        id: 'q-tri-4',
        quizId: 'quiz-triangle',
        questionText: 'The area of a triangle is 30 cm². If its height is 6 cm, what is its base?',
        questionType: 'numerical',
        correctAnswer: '10',
        explanation: 'A = ½bh  →  30 = ½ × b × 6  →  30 = 3b  →  b = 10 cm',
        topicTag: 'triangle-area',
        difficulty: 'medium',
      },
    ],
  },
  {
    id: 'quiz-parallelogram',
    lessonId: 'parallelogram-area',
    title: 'Parallelogram Area Quiz',
    difficulty: 'Beginner',
    questions: [
      {
        id: 'q-para-1',
        quizId: 'quiz-parallelogram',
        questionText: 'A parallelogram has base = 15 cm and height = 9 cm. What is its area?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '67.5 cm²' },
          { id: 'b', text: '48 cm²' },
          { id: 'c', text: '135 cm²' },
          { id: 'd', text: '100 cm²' },
        ],
        correctAnswer: 'c',
        explanation: 'Area = base × height = 15 × 9 = 135 cm²',
        topicTag: 'parallelogram-area',
        difficulty: 'easy',
      },
      {
        id: 'q-para-2',
        quizId: 'quiz-parallelogram',
        questionText: 'In the parallelogram area proof, we cut a triangle and move it. What shape do we get?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: 'Circle' },
          { id: 'b', text: 'Triangle' },
          { id: 'c', text: 'Rectangle' },
          { id: 'd', text: 'Trapezium' },
        ],
        correctAnswer: 'c',
        explanation: 'When we cut the triangle from one side and move it to the other, the parallelogram becomes a rectangle.',
        topicTag: 'parallelogram-derivation',
        difficulty: 'easy',
      },
      {
        id: 'q-para-3',
        quizId: 'quiz-parallelogram',
        questionText: 'Which measurement is used for height in a parallelogram? (NOT the slant side)',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: 'The length of the slant side' },
          { id: 'b', text: 'The perpendicular distance between parallel sides' },
          { id: 'c', text: 'Half of the base' },
          { id: 'd', text: 'The diagonal length' },
        ],
        correctAnswer: 'b',
        explanation: 'The height is the perpendicular (vertical) distance between the two parallel sides, not the slant side.',
        topicTag: 'parallelogram-area',
        difficulty: 'medium',
      },
    ],
  },
  {
    id: 'quiz-trapezium',
    lessonId: 'trapezium-area',
    title: 'Trapezium Area Quiz',
    difficulty: 'Intermediate',
    questions: [
      {
        id: 'q-trap-1',
        quizId: 'quiz-trapezium',
        questionText: 'A trapezium has parallel sides of 8 cm and 12 cm, and height 5 cm. What is its area?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '40 cm²' },
          { id: 'b', text: '50 cm²' },
          { id: 'c', text: '100 cm²' },
          { id: 'd', text: '60 cm²' },
        ],
        correctAnswer: 'b',
        explanation: 'Area = ½(a+b)h = ½(8+12)×5 = ½×20×5 = 50 cm²',
        topicTag: 'trapezium-area',
        difficulty: 'easy',
      },
      {
        id: 'q-trap-2',
        quizId: 'quiz-trapezium',
        questionText: 'In the trapezium proof, what shape is formed by joining two trapeziums?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: 'Rectangle' },
          { id: 'b', text: 'Triangle' },
          { id: 'c', text: 'Parallelogram' },
          { id: 'd', text: 'Circle' },
        ],
        correctAnswer: 'c',
        explanation: 'Two identical trapeziums (one flipped 180°) join to form a parallelogram with base (a+b) and height h.',
        topicTag: 'trapezium-derivation',
        difficulty: 'medium',
      },
    ],
  },
  {
    id: 'quiz-cube',
    lessonId: 'cube',
    title: 'Cube Quiz',
    difficulty: 'Beginner',
    questions: [
      {
        id: 'q-cube-1',
        quizId: 'quiz-cube',
        questionText: 'A cube has side length 4 cm. What is its volume?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '16 cm³' },
          { id: 'b', text: '24 cm³' },
          { id: 'c', text: '64 cm³' },
          { id: 'd', text: '96 cm³' },
        ],
        correctAnswer: 'c',
        explanation: 'Volume = a³ = 4³ = 4 × 4 × 4 = 64 cm³',
        topicTag: 'cube-volume',
        difficulty: 'easy',
      },
      {
        id: 'q-cube-2',
        quizId: 'quiz-cube',
        questionText: 'A cube has side length 3 cm. What is its total surface area?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '27 cm²' },
          { id: 'b', text: '54 cm²' },
          { id: 'c', text: '36 cm²' },
          { id: 'd', text: '18 cm²' },
        ],
        correctAnswer: 'b',
        explanation: 'SA = 6a² = 6 × 3² = 6 × 9 = 54 cm²',
        topicTag: 'cube-surface-area',
        difficulty: 'easy',
      },
      {
        id: 'q-cube-3',
        quizId: 'quiz-cube',
        questionText: 'How many faces does a cube have?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '4' },
          { id: 'b', text: '8' },
          { id: 'c', text: '6' },
          { id: 'd', text: '12' },
        ],
        correctAnswer: 'c',
        explanation: 'A cube has 6 faces, all of which are identical squares.',
        topicTag: 'cube-properties',
        difficulty: 'easy',
      },
    ],
  },
  {
    id: 'quiz-cylinder',
    lessonId: 'cylinder',
    title: 'Cylinder Quiz',
    difficulty: 'Intermediate',
    questions: [
      {
        id: 'q-cyl-1',
        quizId: 'quiz-cylinder',
        questionText: 'A cylinder has radius 5 cm and height 10 cm. What is its volume? (Use π ≈ 3.14)',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '157 cm³' },
          { id: 'b', text: '785 cm³' },
          { id: 'c', text: '314 cm³' },
          { id: 'd', text: '100 cm³' },
        ],
        correctAnswer: 'b',
        explanation: 'V = πr²h = 3.14 × 5² × 10 = 3.14 × 25 × 10 = 785 cm³',
        topicTag: 'cylinder-volume',
        difficulty: 'easy',
      },
      {
        id: 'q-cyl-2',
        quizId: 'quiz-cylinder',
        questionText: 'When the curved surface of a cylinder is unrolled, it forms a:',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: 'Circle' },
          { id: 'b', text: 'Triangle' },
          { id: 'c', text: 'Rectangle' },
          { id: 'd', text: 'Square' },
        ],
        correctAnswer: 'c',
        explanation: 'The curved surface unrolls into a rectangle. Width = 2πr (circumference), Height = h (cylinder height).',
        topicTag: 'cylinder-surface-area',
        difficulty: 'medium',
      },
    ],
  },
  {
    id: 'quiz-cone',
    lessonId: 'cone',
    title: 'Cone Volume Quiz',
    difficulty: 'Intermediate',
    questions: [
      {
        id: 'q-cone-1',
        quizId: 'quiz-cone',
        questionText: 'How many cones of water does it take to fill a cylinder of the same base radius and height?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '1' },
          { id: 'b', text: '2' },
          { id: 'c', text: '3' },
          { id: 'd', text: '4' },
        ],
        correctAnswer: 'c',
        explanation: 'Exactly 3 cones are needed to fill 1 cylinder with the same radius and height. That is why V_cone = ⅓V_cylinder = ⅓πr²h.',
        topicTag: 'cone-volume',
        difficulty: 'easy',
      },
      {
        id: 'q-cone-2',
        quizId: 'quiz-cone',
        questionText: 'A cone has radius 6 cm and height 7 cm. What is its volume? (Use π = 22/7)',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '264 cm³' },
          { id: 'b', text: '792 cm³' },
          { id: 'c', text: '528 cm³' },
          { id: 'd', text: '132 cm³' },
        ],
        correctAnswer: 'a',
        explanation: 'V = ⅓πr²h = ⅓ × (22/7) × 6² × 7 = ⅓ × (22/7) × 36 × 7 = ⅓ × 22 × 36 = ⅓ × 792 = 264 cm³',
        topicTag: 'cone-volume',
        difficulty: 'medium',
      },
    ],
  },
  {
    id: 'quiz-sphere',
    lessonId: 'sphere',
    title: 'Sphere Quiz',
    difficulty: 'Advanced',
    questions: [
      {
        id: 'q-sph-1',
        quizId: 'quiz-sphere',
        questionText: 'The surface area of a sphere equals how many circles of the same radius?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '2 circles' },
          { id: 'b', text: '3 circles' },
          { id: 'c', text: '4 circles' },
          { id: 'd', text: '6 circles' },
        ],
        correctAnswer: 'c',
        explanation: 'SA = 4πr², which is exactly 4 times the area of a circle (πr²). So the sphere\'s surface equals 4 circles.',
        topicTag: 'sphere-surface-area',
        difficulty: 'easy',
      },
      {
        id: 'q-sph-2',
        quizId: 'quiz-sphere',
        questionText: 'A sphere has radius 3 cm. What is its volume? (Use π = 22/7)',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '113.14 cm³' },
          { id: 'b', text: '75.43 cm³' },
          { id: 'c', text: '226.28 cm³' },
          { id: 'd', text: '37.71 cm³' },
        ],
        correctAnswer: 'a',
        explanation: 'V = 4/3 × πr³ = 4/3 × (22/7) × 3³ = 4/3 × (22/7) × 27 = (4 × 22 × 27)/(3 × 7) = 2376/21 ≈ 113.14 cm³',
        topicTag: 'sphere-volume',
        difficulty: 'medium',
      },
    ],
  },
  {
    id: 'quiz-cuboid',
    lessonId: 'cuboid',
    title: 'Cuboid Quiz',
    difficulty: 'Beginner',
    questions: [
      {
        id: 'q-cub-1',
        quizId: 'quiz-cuboid',
        questionText: 'A cuboid has l = 5 cm, w = 4 cm, h = 3 cm. What is its volume?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '47 cm³' },
          { id: 'b', text: '60 cm³' },
          { id: 'c', text: '94 cm³' },
          { id: 'd', text: '120 cm³' },
        ],
        correctAnswer: 'b',
        explanation: 'V = l × w × h = 5 × 4 × 3 = 60 cm³',
        topicTag: 'cuboid-volume',
        difficulty: 'easy',
      },
      {
        id: 'q-cub-2',
        quizId: 'quiz-cuboid',
        questionText: 'A cuboid has l = 5 cm, w = 4 cm, h = 3 cm. What is its total surface area?',
        questionType: 'MCQ',
        options: [
          { id: 'a', text: '60 cm²' },
          { id: 'b', text: '74 cm²' },
          { id: 'c', text: '94 cm²' },
          { id: 'd', text: '120 cm²' },
        ],
        correctAnswer: 'c',
        explanation: 'SA = 2(lw + wh + lh) = 2(5×4 + 4×3 + 5×3) = 2(20+12+15) = 2×47 = 94 cm²',
        topicTag: 'cuboid-surface-area',
        difficulty: 'medium',
      },
    ],
  },
]

export function getQuizByLessonId(lessonId: string): Quiz | undefined {
  return quizzes.find((q) => q.lessonId === lessonId)
}

export function getQuizById(quizId: string): Quiz | undefined {
  return quizzes.find((q) => q.id === quizId)
}
